language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - zip -r moira ./*
  - mkdir -p deploy
  - mv moira.zip deploy/moira.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    edge: true

    bucket: moira-springboot
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait_until_deployed : true
    on:
      branch: master

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    edge: true

    bucket: moira-springboot
    key : moira.zip

    bundle_type : zip
    application : moira

    deplyment_group : moira-group
    region: ap-northeast-2
    wait-until-deployed : true

    on:
      branch: master

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - kimsw1726@gmail.com