spring:
  profiles:
    active: local
    group:
      local: jwt, aws
      set1: real-db, jwt
      set2: real-db, jwt

logging:
  level:
    root: info
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

cloud:
  aws:
    s3:
      bucket: moira-springboot
    region:
      static: ap-northeast-2
    stack:
      auto: false
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:moira;
    username: sa
    password:
---
spring:
  config:
    activate:
      on-profile: set1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: set2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
server:
  port: 8082

