spring:
  profiles:
    active: local
    group:
      set1: real-db
      set2: real-db

logging:
  level:
    root: info
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:moira;
    username: sa
    password:

---
spring:
  config:
    activate:
      on-profile: set1

server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: set2

server:
  port: 8082

